import {
  CONSTS as LIB_CONSTS,
  EXAMPLE_JSON_BLUE_SKIES as LIB_EXAMPLE_JSON_BLUE_SKIES,
} from "gabby-query-protocol-lib";

import {
  CONSTS as PROJECTION_CONSTS,
  EXAMPLE_JSON_BLUE_SKIES as PROJECTION_EXAMPLE_JSON_BLUE_SKIES,
} from "gabby-query-protocol-projection";

const GABBY_EXAMPLE_JSON_BLUE_SKIES = {
  LIB: LIB_EXAMPLE_JSON_BLUE_SKIES,
  PROJECTION: PROJECTION_EXAMPLE_JSON_BLUE_SKIES,
};

const GABBY_CONSTS = {
  LIB: LIB_CONSTS,
  PROJECTION: PROJECTION_CONSTS,
};

export { GABBY_EXAMPLE_JSON_BLUE_SKIES, GABBY_CONSTS };
